### ISSUE TITLE
Batch parameter estimates

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#113]
# Summary

As a user I would like to be able to pass multiple model summary objects, or a summary log tibble, to the `param_estimates()` function and get back a table containing the parameter estimates for each model. Specifically: a long table with a columns for:

* model identifier
* parameter name
* parameter estimate

# Tests
- tests/testthat/test-param-estimates.R
  - param_estimates.bbi_summary_list gets expected table
  - param_estimates.bbi_summary_log_df gets expected table

**Comment by copernican** [comment]
> I would like to be able to pass multiple models (or model summary objects)

How much flexibility do we need? `param_estimates()` currently takes only a `bbi_{.model_type}_summary` object. Do we want to build in the flexibility to take models as well, or can we provide a workflow that looks like

```r
mods %>%
  model_summaries() %>%
  param_estimates()
```

which simplifies what this function needs to do. If we do need to support models, do we need to support the four types of arguments allowed for the `.mods` argument to `model_summaries()`? Is the user allowed to pass a list that includes different types of model specifications, e.g., one element is a model summary, another is a character?

> to the `param_estimates()` function

Does this mean that we will change the existing function signature, so that `.summary` can have multiple elements? Or are we contemplating writing a new function that essentially wraps `map()`? Or some other option?

> get back a table with each parameter as a column and each model as a row

This tibble could be quite wide. And, is it possible that not all parameters will be available for all models (leading to `NA`s)? Would it be better to return a tibble whose rows are something like

```
model_id | parameter | value
```

and then let the user pivot that table as desired?

**Comment by seth127** [comment]
Good catch, that was written wrong: we will _not_ be accepting models directly. I changed the original. It now reads:
`pass multiple model summary objects, or summary log tibble`

To the other question, we will need to get some clarification from the scientists. Questions that need answers:

* Will you ever want to run this on models with different numbers of params (or different param definitions)? 
* If so, what should happen? Would you want wide with NA's or would a long table be better? 
* If not, should the function error if there are different numbers of params? That feels aggressive, but if it really should _never_ happen then that's probably safest.

**Comment by seth127** [comment]
@copernican in response to

> This tibble could be quite wide... let the user pivot that table as desired?

I talked to scientists and general consensus is that leaving it as a long table is the safest and easiest thing to do. I added a comment in the docs to give an example of how to easily convert it to wide (since that was the original ask, and probably the most common use case). https://github.com/metrumresearchgroup/rbabylon/pull/120/files#diff-09071e1e13d76576ab92ab3c8a2e1b40R30
