### ISSUE TITLE
synchronize flags with snake case update in babylon

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#16]
@shairozan can you think of a good way to test whether the flags here are in sync with what's in babylon? Like, is there a way for `bbi --help` to return something machine readable that I could test against?

@dpastoor is that kind of testing necessary? It does seem like we should have some way to make sure these flags stay in sync, but it's not obvious to me how to do it.

**Comment by shairozan** [comment]
It may be possible with some black magic. Cobra exposes a `HelpTemplate` that a user can define. What we could do is define / reverse engineer the existing template such that if -json is passed, help would generate just an object of json values. That way you could basically go over them key by key and see if you have any gaps, especially for key components you're looking for. 

Requires a lot more looking since I don't even know where in cobra the default template is. Gotta figure out they're getting the merged flags.

**Comment by seth127** [comment]
@dpastoor you make the call as to whether we want @shairozan to look into the solution he mentioned. If not, the keys are currently in sync (based on my own manual checking) but we won't have any programmatic guarantees that they stay in sync.

**Comment by shairozan** [comment]
You kind of will have programmatic guarantees through drone builds. You could have that as a step of testing if I can get it to work, where it would pull latest for babylon and then look at the keys, iterate over them and make sure you that the keys you are using appear in the output

**Comment by seth127** [comment]
I'm putting this on the "roadmap" for the future. As of now they are manually synchronized, but there is no testing to ensure it stays that way.

**Comment by seth127** [comment]
Closing this because the most likely path forward for this issue is captured in https://github.com/metrumresearchgroup/rbabylon/issues/171
