### ISSUE TITLE
Define new .config_path handling

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#172]
`.config_path` used to default to looking for a `babylon.yaml` file in `model_directory`. Now it should look in `file.path(.mod[[WORKING_DIR]], "babylon.yaml")` by default, or a user can pass a path _relative_ to their working directory.

**Comment by seth127** [comment]
Seth notes:

* Change default value
* Modify `find_config_file_path()` for new logic
* Any other internal function logic? (hopefully not)
* Any tests? Maybe for find_config_file_path? (probably internal…)

**Comment by seth127** [comment]
Note: for `submit_models` (plural) behavior will be:
* default to looking for `babylon.yaml` in _each model's_ respective working directory
  * this will be true because in #205 we will group models by their working directory
* if a path is passed to `.config_path` then that config will be used for _all_ models

**Comment by copernican** [comment]
Spec is WIP

We have deprecated the `model_working_directory` element of a model object as discussed in #182. But, the desired behavior is to keep `.config_path` as an optional argument, and to attempt to use a `babylon.yaml` found in the model working directory in the default case. One pattern for these changes could therefore be

```r
f <- function(mod, config_path = file.path(get_model_working_directory(mod), "babylon.yaml") {
  # things involving config_path
}
```

but this would 

- require exporting `get_model_working_directory()`

- mean that the concept of a working directory is part of the API rather than an implementation detail

neither of which is desirable. While we usually prefer to have `NULL` handling be explicit, in this case we may prefer a pattern like

```r
f <- function(mod, config_path = NULL) {
  if (is.null(config_path)) {
    config_path <- file.path(get_model_working_directory(mod), "babylon.yaml")
  }
  # things involving config_path
}
```

coupled with a description of the `config_path` argument as

> Path to a babylon configuration file. If `NULL`, will attempt to use a `babylon.yaml` in the same directory as the model.

In the case of `submit_nonmem_models()`, we can use a similar pattern to replace the existing assignment to `.config_path`:

```r
if (is.null(.config_path)) {
  .config_path <- file.path(model_dir, "babylon.yaml")
} else {
  .config_path <- normalizePath(.config_path, mustWork = TRUE)
}
```

# Technical specification

`submit_model()`
`submit_model.bbi_nonmem_model()`
`submit_nonmem_model()`

`submit_models()`
`submit_models.list()`
`submit_nonmem_models()`

`find_config_file_path()`

`bbi_init()`

# Test changes

**Comment by seth127** [comment]
I don't have a problem with making `get_model_working_directory()` public, and honestly I think I might recommend it (and possibly also implementing a `bbi_log_df` dispatch like the other getters have). I don't think this is any different in principle than our other getters: it doesn't expose the internals of the model object to the user in any way, it just uses the model object to build a path (in this case, to the directory that the model files are sitting in) that could potentially be useful for a user.

If you agree with that, I think I like your option:
```
f <- function(mod, config_path = file.path(get_model_working_directory(mod), "babylon.yaml") {
  # things involving config_path
}
```

The `NULL` option is fine too, but I think exposing this is more explicit and obvious for a user to understand, even just by looking at the function signature.
