### ISSUE TITLE
save_model_yaml delete .out_path arg

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#181]
`save_model_yaml()` is a private function that has an `.out_path` argument which allows it to save the YAML file to a path _other than_ the one contained in `.mod[[YAML_YAML_PATH]]`. As a result of #141 this will no longer be allowed, so this argument should be deprecated.

## Acceptance Criteria

* delete `.out_path` arg from `save_model_yaml()`
* delete `.out_path` arg from anywhere `save_model_yaml()` is called.
* ensure that anywhere that _used to_ call `save_model_yaml()` with `.out_path` does in fact set `.mod[[YAML_YAML_PATH]]` correctly before passing it `.mod` to `save_model_yaml()`
* update `save_model_yaml()` docs accordingly

**Comment by seth127** [comment]
This is mentioned in part 5 of this comment https://github.com/metrumresearchgroup/rbabylon/issues/179#issuecomment-697842274

**Comment by copernican** [comment]
We should consider having `save_model_yaml()` return the path to the YAML file it just wrote, invisibly.

**Comment by copernican** [comment]
# Technical specification

1. Remove `.out_path` argument to `save_model_yaml()`.

2. Replace check that `.out_path` is `NULL` to simply

    ```r
    .out_path <- get_yaml_path(.mod, .check_exists = FALSE)
    ```

    Note that #182 will change the structure of the model object, but this code should continue to work because we will change `get_yaml_path()` at that time to reflect the new structure.

3. Modify call to `save_model_yaml()` in `new_model()` to reflect that `.out_path` is deprecated. Note that `save_model_yaml()` will still behave as expected because internally it calls `get_yaml_path()`, which references the `orig_yaml_file` element of its argument `.mod`.

4. Modify call to `save_model_yaml()` in `copy_model_from()` to reflect that `.out_path` is deprecated. Again, the call will continue to work for the same reason as (3).

# Test changes

No tests are expected to be affected by this change, because `save_model_yaml()` is not exported and therefore not currently covered by tests.
