### ISSUE TITLE
import and parse model results as json

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/rbabylon#2]
Create a function with similar syntax to existing `jsonlite::read_json()` function which takes a json object output from Babylon as argument and creates a `run_results` object.

**Proposed syntax:**
`res <- read_results("examples/101.json")`
`res <- read_results(101, dir="examples")`

**Input:** 
JSON file containing information from NONMEM run. This will be produced by a call to `bbi nonmem summary --json`

**Output:**
A `list` of `list`s for post-processing: theta_df, omega_df, sigma_df, run_details, etc.

Converting each of these to separate `data.frame`s suitable for downstream use (e.g. get_estimate_table(), get_shrinkage_table()) will be part of future issues.

# Tests
* tests/testthat/test-summary.R
  * model_summary.bbi_nonmem_model produces expected output
  * model_summary.character produces expected output
  * model_summary.numeric produces expected output
  * model_summary() fails predictably if it can't find some parts (i.e. model isn't finished)
  * model_summary() fails predictably if no .lst file present
* tests/testthat/test-workflow-composable-bbi.R
  * step by step create_model to submit_model to model_summary works

**Comment by callistosp** [comment]
@dpastoor I'm confused about the structure of this json. I see that `parameter_data` contains an array of objects, I'm assuming to separate estimates/std_err from different runs as objects in the array. However, looking at the other objects (e.g. `parameter_names`, `shrinkage_details`), they do not share this same structure, and only contain a single object instead of an array. Is this correct?

**Comment by callistosp** [comment]
also it would help if the `parameter_structures` parameter names were not capitalized to match the rest of the data structure

**Comment by seth127** [comment]
@dpastoor and @callistosp am I right that we should close this (very old) issue and call it complete. We can indeed get the model summary into a list in R. Furthermore, any questions about the structure of that json really belong in https://github.com/metrumresearchgroup/babylon/issues because `rbabylon` is just reading in the json output from `bbi nonmem summary`. Do you guys agree?

I also put a similar comment in https://github.com/metrumresearchgroup/rbabylon/issues/2 but I think we should start collecting issues for what we want to be able to easily parse from this summary object.

Anyway, if we're cool with this closing, we can attach these tests to the issue:
# Tests
* tests/testthat/test-summary.R
  * model_summary() produces expected list object
  * model_summary() fails predictably if it can't find some parts (i.e. model isn't finished)
  * model_summary() fails predictably if no .lst file present
* tests/testthat/test-workflow-composable-bbi.R
  * step by step create_model to submit_model to model_summary works

**Comment by callistosp** [comment]
yes @seth127, the current functionality addresses this need. Thanks for cleaning up the repo
