### ISSUE TITLE
add_summary errors if all summaries fail

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#279]
If a user calls `run_log() %>% add_summary()` and _none_ of the summaries complete it will throw this very obtuse error
```
Error: Can't subset columns that don't exist.
x Column `run` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In .impl_func(mod_list, ...) :
```

## situation

This will have in both of the following plausible situations

* the user has not correctly set `options('rbabylon.bbi_exe_path')` so model_summary() can't find it and all the summaries fail
* the user is running a batch of models and none of them has finished yet

In both cases, some kind of error _may_ be appropriate. But not the one currently being thrown.

## potential cause
I'm pretty sure this happens because, when no summaries complete, the `bbi_summary_log_df` comes back with only two columns: `absolute_model_path` and `error_msg`.  The most obvious way to fix this is to construct the `run` column even if everything fails, but there may be a better approach too.

**Comment by copernican** [comment]
Why do you consider this a bug?

**Comment by seth127** [comment]
because it's unexpected and undesirable behavior

**Comment by copernican** [comment]
I can reproduce the error. As you say, it is a consequence of the `run` column not existing in the tibble returned by `summary_log_impl()`. Thus, the `select(-{{RUN_ID_COL}})` call in `add_log_impl()` doesn't find the column, and throws the error you describe. I think the problem warrants some discussion, because it seems to be a design question: `add_log_impl()` is assuming things about the structure of what is returned by `summary_log_impl()` that are not guaranteed, either by the documentation or in practice. Granted, the `*_impl()` functions are `@internal`, so we have some flexibility with how they behave, but it may be worth fleshing this out a bit more.
